vast:
  aging-frequency: 24h
  aging-query: ''
  catalog-fp-rate: 0.01
  console: automatic
  console-format: '%^[%T.%e] %v%$'
  console-verbosity: info
  db-directory: vast.db
  disable-log-rotation: false
  enable-metrics: false
  endpoint: 192.168.1.1:4000
  file-format: '[%Y-%m-%dT%T.%e%z] [%n] [%l] [%s=%#] %v'
  file-verbosity: info
  log-file: vast.db/server.log
  log-queue-size: 1000000
  log-rotation-threshold: 10MiB
  max-partition-size: 1048576
  max-queries: 10
  max-resident-partitions: 10
  max-segment-size: 1024
  max-taste-partitions: 5
  metrics:
    file-sink:
      enable: false
      path: vast.db/vast-metrics.log
      real-time: false
    self-sink:
      enable: true
      slice-size: 128
      slice-type: arrow
    uds-sink:
      enable: false
      path: vast.db/vast-metrics.sock
      real-time: false
      type: datagram
  node: false
  node-id: node
  plugin-dirs: []
  plugins: []
  print-endpoint: true
  schema-dirs: []
  segments: 10
  start:
    print-endpoint: false
  store-backend: segment-store
