services:
  connector-export-file-csv:
    depends_on:
    - opencti
    environment:
      APP__ADMIN__EMAIL: ${OPENCTI_ADMIN_EMAIL}
      APP__ADMIN__PASSWORD: ${OPENCTI_ADMIN_PASSWORD}
      APP__ADMIN__TOKEN: ${OPENCTI_ADMIN_TOKEN}
      APP__APP_LOGS__LOGS_LEVEL: error
      APP__PORT: '8080'
      CONNECTOR_CONFIDENCE_LEVEL: 15
      CONNECTOR_ID: ${CONNECTOR_EXPORT_FILE_CSV_ID}
      CONNECTOR_LOG_LEVEL: info
      CONNECTOR_NAME: ExportFileCsv
      CONNECTOR_SCOPE: text/plain
      CONNECTOR_TYPE: INTERNAL_EXPORT_FILE
      ELASTICSEARCH__URL: http://elasticsearch:9200
      MINIO__ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO__ENDPOINT: minio
      MINIO__PORT: '9000'
      MINIO__SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO__USE_SSL: 'false'
      NODE_OPTIONS: --max-old-space-size=8096
      PROVIDERS__LOCAL__STRATEGY: LocalStrategy
      RABBITMQ__HOSTNAME: rabbitmq
      RABBITMQ__MANAGEMENT_SSL: 'false'
      RABBITMQ__PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ__PORT: '5672'
      RABBITMQ__PORT_MANAGEMENT: '15672'
      RABBITMQ__USERNAME: ${RABBITMQ_DEFAULT_USER}
      REDIS__HOSTNAME: redis
      REDIS__PORT: '6379'
      SMTP__HOSTNAME: ${SMTP_HOSTNAME}
      SMTP__PORT: '25'
    image: opencti/connector-export-file-csv:5.2.3
    restart: always
  connector-export-file-stix:
    depends_on:
    - opencti
    environment:
      APP__ADMIN__EMAIL: ${OPENCTI_ADMIN_EMAIL}
      APP__ADMIN__PASSWORD: ${OPENCTI_ADMIN_PASSWORD}
      APP__ADMIN__TOKEN: ${OPENCTI_ADMIN_TOKEN}
      APP__APP_LOGS__LOGS_LEVEL: error
      APP__PORT: '8080'
      CONNECTOR_CONFIDENCE_LEVEL: 15
      CONNECTOR_ID: ${CONNECTOR_EXPORT_FILE_STIX_ID}
      CONNECTOR_LOG_LEVEL: info
      CONNECTOR_NAME: ExportFileCsv
      CONNECTOR_SCOPE: text/csv
      CONNECTOR_TYPE: INTERNAL_EXPORT_FILE
      ELASTICSEARCH__URL: http://elasticsearch:9200
      MINIO__ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO__ENDPOINT: minio
      MINIO__PORT: '9000'
      MINIO__SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO__USE_SSL: 'false'
      NODE_OPTIONS: --max-old-space-size=8096
      PROVIDERS__LOCAL__STRATEGY: LocalStrategy
      RABBITMQ__HOSTNAME: rabbitmq
      RABBITMQ__MANAGEMENT_SSL: 'false'
      RABBITMQ__PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ__PORT: '5672'
      RABBITMQ__PORT_MANAGEMENT: '15672'
      RABBITMQ__USERNAME: ${RABBITMQ_DEFAULT_USER}
      REDIS__HOSTNAME: redis
      REDIS__PORT: '6379'
      SMTP__HOSTNAME: ${SMTP_HOSTNAME}
      SMTP__PORT: '25'
    image: opencti/connector-export-file-stix:5.2.3
    restart: always
  connector-export-file-txt:
    depends_on:
    - opencti
    environment:
      APP__ADMIN__EMAIL: ${OPENCTI_ADMIN_EMAIL}
      APP__ADMIN__PASSWORD: ${OPENCTI_ADMIN_PASSWORD}
      APP__ADMIN__TOKEN: ${OPENCTI_ADMIN_TOKEN}
      APP__APP_LOGS__LOGS_LEVEL: error
      APP__PORT: '8080'
      CONNECTOR_CONFIDENCE_LEVEL: 15
      CONNECTOR_ID: ${CONNECTOR_EXPORT_FILE_TXT_ID}
      CONNECTOR_LOG_LEVEL: info
      CONNECTOR_NAME: ExportFileTxt
      CONNECTOR_SCOPE: text/plain
      CONNECTOR_TYPE: INTERNAL_EXPORT_FILE
      ELASTICSEARCH__URL: http://elasticsearch:9200
      MINIO__ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO__ENDPOINT: minio
      MINIO__PORT: '9000'
      MINIO__SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO__USE_SSL: 'false'
      NODE_OPTIONS: --max-old-space-size=8096
      PROVIDERS__LOCAL__STRATEGY: LocalStrategy
      RABBITMQ__HOSTNAME: rabbitmq
      RABBITMQ__MANAGEMENT_SSL: 'false'
      RABBITMQ__PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ__PORT: '5672'
      RABBITMQ__PORT_MANAGEMENT: '15672'
      RABBITMQ__USERNAME: ${RABBITMQ_DEFAULT_USER}
      REDIS__HOSTNAME: redis
      REDIS__PORT: '6379'
      SMTP__HOSTNAME: ${SMTP_HOSTNAME}
      SMTP__PORT: '25'
    image: opencti/connector-export-file-txt:5.2.3
    restart: always
  connector-history:
    depends_on:
    - opencti
    environment:
      APP__ADMIN__EMAIL: ${OPENCTI_ADMIN_EMAIL}
      APP__ADMIN__PASSWORD: ${OPENCTI_ADMIN_PASSWORD}
      APP__ADMIN__TOKEN: ${OPENCTI_ADMIN_TOKEN}
      APP__APP_LOGS__LOGS_LEVEL: error
      APP__PORT: '8080'
      CONNECTOR_CONFIDENCE_LEVEL: 15
      CONNECTOR_ID: ${CONNECTOR_HISTORY_ID}
      CONNECTOR_LOG_LEVEL: info
      CONNECTOR_NAME: History
      CONNECTOR_SCOPE: history
      CONNECTOR_TYPE: STREAM
      ELASTICSEARCH__URL: http://elasticsearch:9200
      MINIO__ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO__ENDPOINT: minio
      MINIO__PORT: '9000'
      MINIO__SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO__USE_SSL: 'false'
      NODE_OPTIONS: --max-old-space-size=8096
      PROVIDERS__LOCAL__STRATEGY: LocalStrategy
      RABBITMQ__HOSTNAME: rabbitmq
      RABBITMQ__MANAGEMENT_SSL: 'false'
      RABBITMQ__PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ__PORT: '5672'
      RABBITMQ__PORT_MANAGEMENT: '15672'
      RABBITMQ__USERNAME: ${RABBITMQ_DEFAULT_USER}
      REDIS__HOSTNAME: redis
      REDIS__PORT: '6379'
      SMTP__HOSTNAME: ${SMTP_HOSTNAME}
      SMTP__PORT: '25'
    image: opencti/connector-history:5.2.3
    restart: always
  connector-import-document:
    depends_on:
    - opencti
    environment:
      APP__ADMIN__EMAIL: ${OPENCTI_ADMIN_EMAIL}
      APP__ADMIN__PASSWORD: ${OPENCTI_ADMIN_PASSWORD}
      APP__ADMIN__TOKEN: ${OPENCTI_ADMIN_TOKEN}
      APP__APP_LOGS__LOGS_LEVEL: error
      APP__PORT: '8080'
      CONNECTOR_AUTO: 'true'
      CONNECTOR_CONFIDENCE_LEVEL: 15
      CONNECTOR_ID: ${CONNECTOR_IMPORT_DOCUMENT_ID}
      CONNECTOR_LOG_LEVEL: info
      CONNECTOR_NAME: ImportDocument
      CONNECTOR_ONLY_CONTEXTUAL: 'false'
      CONNECTOR_SCOPE: application/pdf,text/plain,text/html
      CONNECTOR_TYPE: INTERNAL_IMPORT_FILE
      CONNECTOR_VALIDATE_BEFORE_IMPORT: 'true'
      ELASTICSEARCH__URL: http://elasticsearch:9200
      IMPORT_DOCUMENT_CREATE_INDICATOR: 'true'
      MINIO__ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO__ENDPOINT: minio
      MINIO__PORT: '9000'
      MINIO__SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO__USE_SSL: 'false'
      NODE_OPTIONS: --max-old-space-size=8096
      PROVIDERS__LOCAL__STRATEGY: LocalStrategy
      RABBITMQ__HOSTNAME: rabbitmq
      RABBITMQ__MANAGEMENT_SSL: 'false'
      RABBITMQ__PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ__PORT: '5672'
      RABBITMQ__PORT_MANAGEMENT: '15672'
      RABBITMQ__USERNAME: ${RABBITMQ_DEFAULT_USER}
      REDIS__HOSTNAME: redis
      REDIS__PORT: '6379'
      SMTP__HOSTNAME: ${SMTP_HOSTNAME}
      SMTP__PORT: '25'
    image: opencti/connector-import-document:5.2.3
    restart: always
  connector-import-file-stix:
    depends_on:
    - opencti
    environment:
      APP__ADMIN__EMAIL: ${OPENCTI_ADMIN_EMAIL}
      APP__ADMIN__PASSWORD: ${OPENCTI_ADMIN_PASSWORD}
      APP__ADMIN__TOKEN: ${OPENCTI_ADMIN_TOKEN}
      APP__APP_LOGS__LOGS_LEVEL: error
      APP__PORT: '8080'
      CONNECTOR_AUTO: 'true'
      CONNECTOR_CONFIDENCE_LEVEL: 15
      CONNECTOR_ID: ${CONNECTOR_IMPORT_FILE_STIX_ID}
      CONNECTOR_LOG_LEVEL: info
      CONNECTOR_NAME: ImportFileStix
      CONNECTOR_SCOPE: application/json,text/xml
      CONNECTOR_TYPE: INTERNAL_IMPORT_FILE
      CONNECTOR_VALIDATE_BEFORE_IMPORT: 'true'
      ELASTICSEARCH__URL: http://elasticsearch:9200
      MINIO__ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO__ENDPOINT: minio
      MINIO__PORT: '9000'
      MINIO__SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO__USE_SSL: 'false'
      NODE_OPTIONS: --max-old-space-size=8096
      PROVIDERS__LOCAL__STRATEGY: LocalStrategy
      RABBITMQ__HOSTNAME: rabbitmq
      RABBITMQ__MANAGEMENT_SSL: 'false'
      RABBITMQ__PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ__PORT: '5672'
      RABBITMQ__PORT_MANAGEMENT: '15672'
      RABBITMQ__USERNAME: ${RABBITMQ_DEFAULT_USER}
      REDIS__HOSTNAME: redis
      REDIS__PORT: '6379'
      SMTP__HOSTNAME: ${SMTP_HOSTNAME}
      SMTP__PORT: '25'
    image: opencti/connector-import-file-stix:5.2.3
    restart: always
  elasticsearch:
    environment:
    - discovery.type=single-node
    - xpack.ml.enabled=false
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    restart: always
    ulimits:
      memlock:
        hard: '-1'
        soft: '-1'
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - esdata:/usr/share/elasticsearch/data
  minio:
    command: server /data
    environment:
      MINIO__ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO__ENDPOINT: minio
      MINIO__PORT: '9000'
      MINIO__SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO__USE_SSL: 'false'
    healthcheck:
      interval: 30s
      retries: 3
      test:
      - CMD
      - curl
      - -f
      - http://localhost:9000/minio/health/live
      timeout: 20s
    image: minio/minio:RELEASE.2022-02-26T02-54-46Z
    ports:
    - 9000:9000
    restart: always
    volumes:
    - s3data:/data
  opencti:
    depends_on:
    - redis
    - elasticsearch
    - minio
    - rabbitmq
    environment:
      APP__ADMIN__EMAIL: ${OPENCTI_ADMIN_EMAIL}
      APP__ADMIN__PASSWORD: ${OPENCTI_ADMIN_PASSWORD}
      APP__ADMIN__TOKEN: ${OPENCTI_ADMIN_TOKEN}
      APP__APP_LOGS__LOGS_LEVEL: error
      APP__PORT: '8080'
      ELASTICSEARCH__URL: http://elasticsearch:9200
      MINIO__ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO__ENDPOINT: minio
      MINIO__PORT: '9000'
      MINIO__SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO__USE_SSL: 'false'
      NODE_OPTIONS: --max-old-space-size=8096
      PROVIDERS__LOCAL__STRATEGY: LocalStrategy
      RABBITMQ__HOSTNAME: rabbitmq
      RABBITMQ__MANAGEMENT_SSL: 'false'
      RABBITMQ__PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ__PORT: '5672'
      RABBITMQ__PORT_MANAGEMENT: '15672'
      RABBITMQ__USERNAME: ${RABBITMQ_DEFAULT_USER}
      REDIS__HOSTNAME: redis
      REDIS__PORT: '6379'
      SMTP__HOSTNAME: ${SMTP_HOSTNAME}
      SMTP__PORT: '25'
    image: opencti/platform:5.2.3
    ports:
    - 8080:8080
    restart: always
  rabbitmq:
    environment:
      RABBITMQ__HOSTNAME: rabbitmq
      RABBITMQ__MANAGEMENT_SSL: 'false'
      RABBITMQ__PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ__PORT: '5672'
      RABBITMQ__PORT_MANAGEMENT: '15672'
      RABBITMQ__USERNAME: ${RABBITMQ_DEFAULT_USER}
    image: rabbitmq:3.9-management
    restart: always
    volumes:
    - amqpdata:/var/lib/rabbitmq
  redis:
    image: redis:6.2.6
    restart: always
    volumes:
    - redisdata:/data
  worker:
    depends_on:
    - opencti
    deploy:
      mode: replicated
      replicas: 3
    environment:
      OPENCTI_TOKEN: ${OPENCTI_ADMIN_TOKEN}
      OPENCTI_URL: http://opencti:8080
      WORKER_LOG_LEVEL: info
    image: opencti/worker:5.2.3
    restart: always
version: '3'
volumes:
  amqpdata: null
  esdata: null
  redisdata: null
  s3data: null
