services:
  elasticsearch:
    environment:
    - discovery.type=single-node
    - xpack.ml.enabled=false
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    restart: always
    volumes:
    - esdata:/usr/share/elasticsearch/data
  minio:
    command: server /data
    environment:
      MINIO__ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO__ENDPOINT: minio
      MINIO__PORT: '9000'
      MINIO__SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO__USE_SSL: 'false'
    healthcheck:
      interval: 30s
      retries: 3
      test:
      - CMD
      - curl
      - -f
      - http://localhost:9000/minio/health/live
      timeout: 20s
    image: minio/minio:RELEASE.2022-02-26T02-54-46Z
    ports:
    - 9000:9000
    restart: always
    volumes:
    - s3data:/data
  opencti:
    depends_on:
    - redis
    - elasticsearch
    - minio
    - rabbitmq
    environment:
      APP__ADMIN__EMAIL: ${OPENCTI_ADMIN_EMAIL}
      APP__ADMIN__PASSWORD: ${OPENCTI_ADMIN_PASSWORD}
      APP__ADMIN__TOKEN: ${OPENCTI_ADMIN_TOKEN}
      APP__APP_LOGS__LOGS_LEVEL: error
      APP__PORT: '8080'
      ELASTICSEARCH__URL: http://elasticsearch:9200
      MINIO__ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO__ENDPOINT: minio
      MINIO__PORT: '9000'
      MINIO__SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO__USE_SSL: 'false'
      NODE_OPTIONS: --max-old-space-size=8096
      PROVIDERS__LOCAL__STRATEGY: LocalStrategy
      RABBITMQ__HOSTNAME: rabbitmq
      RABBITMQ__MANAGEMENT_SSL: 'false'
      RABBITMQ__PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ__PORT: '5672'
      RABBITMQ__PORT_MANAGEMENT: '15672'
      RABBITMQ__USERNAME: ${RABBITMQ_DEFAULT_USER}
      REDIS__HOSTNAME: redis
      REDIS__PORT: '6379'
      SMTP__HOSTNAME: ${SMTP_HOSTNAME}
      SMTP__PORT: '25'
    image: opencti/platform:5.2.3
    restart: always
  rabbitmq:
    environment:
      RABBITMQ__HOSTNAME: rabbitmq
      RABBITMQ__MANAGEMENT_SSL: 'false'
      RABBITMQ__PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ__PORT: '5672'
      RABBITMQ__PORT_MANAGEMENT: '15672'
      RABBITMQ__USERNAME: ${RABBITMQ_DEFAULT_USER}
    image: rabbitmq:3.9-management
    restart: always
    volumes:
    - amqpdata:/var/lib/rabbitmq
  redis:
    image: redis:6.2.6
    restart: always
    volumes:
    - redisdata:/data
version: '3'
volumes:
  amqpdata: null
  esdata: null
  redisdata: null
  s3data: null
